name: "Release"
on:
  push:
    tags:
      - "*.*"

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "NPM Install"
        run: npm install

      - name: "Compile"
        run: npm run compile

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1.3
        with:
          cmd: build
          source: ext

      - name: "web-ext sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1.3
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: listed
          apiKey: ${{ secrets.FIREFOX_API_KEY }}
          apiSecret: ${{ secrets.FIREFOX_API_SECRET }}

      - name: "Create Release"
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.web-ext-sign.outputs.target || steps.web-ext-build.outputs.target }}
